In [3]:
import numpy as np
import pandas as pd 

In [4]:
#null vector 
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#memory of array 
a = np.zeros(10)
a.nbytes

80

In [7]:
#fifth value is 1
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
#array usng range 
a = np.arange(10,15)
a

array([10, 11, 12, 13, 14])

In [10]:
#reverse array
a = np.array([10, 11, 12, 13, 14])
b = np.flip(a)
b

array([14, 13, 12, 11, 10])

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
add = np.add(a,b)
sub = np.subtract(a,b)
div = np.divide(a,b)
mult = np.multiply(a,b)
print(add, sub, div, mult)

[ 6  8 10 12] [-4 -4 -4 -4] [0.2        0.33333333 0.42857143 0.5       ] [ 5 12 21 32]


In [14]:
#round integer 
a = np.array([3.14, 2.71, 7.65, 5.49, 1.23])
b = np.round(a)
b

array([3., 3., 8., 5., 1.])

In [15]:
#ceil and floor 
a = np.array([3.14, 2.71, 7.65, 5.49, 1.23])
b = np.floor(a)
c = np.ceil(a)
print(b,c)

[3. 2. 7. 5. 1.] [4. 3. 8. 6. 2.]


In [16]:
#degree to radian 
a = np.array([11,22,33,44,55])
b = np.radians(a)
b

array([0.19198622, 0.38397244, 0.57595865, 0.76794487, 0.95993109])

In [18]:
#3x3 matric 
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
#reverse 2D array 
a = np.array([[2,1,0],[5,4,3],[8,7,6]])
b = np.flip(a)
b

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [20]:
a = np.array([[2,1,0],[5,4,3],[8,7,6]])
b = np.flip(a, axis=1)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
#remove non zero elements from zero 
a = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [22]:
#deteminant or arrray 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.linalg.det(a)
b

0.0

In [24]:
#inverse
a = np.array([[1,2,3],[0,5,6],[7,8,9]])
b = np.linalg.inv(a)
b

array([[ 0.125     , -0.25      ,  0.125     ],
       [-1.75      ,  0.5       ,  0.25      ],
       [ 1.45833333, -0.25      , -0.20833333]])

In [25]:
#random vector and mean 
a = np.random.rand(30)
b = np.mean(a)
b

0.6041713466963063

In [26]:
#extract elelmnt from range in array 
a = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])
l = 20
u = 40
b = a[(a>=l) & (a<=u)]
b

array([20, 25, 30, 35, 40])

In [27]:
#3x3x3 array 
a = np.random.rand(3,3,3)
a

array([[[0.86017512, 0.74207826, 0.05916175],
        [0.20413299, 0.94096411, 0.84993711],
        [0.54335439, 0.37297714, 0.38489915]],

       [[0.56850777, 0.26201196, 0.93116644],
        [0.6780506 , 0.71858791, 0.83776447],
        [0.30178873, 0.31953292, 0.76276576]],

       [[0.47732403, 0.80533848, 0.2336739 ],
        [0.14881681, 0.93724893, 0.63880971],
        [0.52990384, 0.78871787, 0.54177263]]])

In [28]:
a = np.random.rand(10,10)
minn = np.min(a)
maxx = np.max(a)
print(minn,maxx)

0.0024338314262064564 0.9997501346905906


In [29]:
#identity matrix 
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
#doct product 
a = np.random.rand(5,3)
b = np.random.rand(3,2)
c = np.dot(a,b)
c

array([[0.7891851 , 0.17997715],
       [1.10456409, 0.62362246],
       [0.97876434, 0.76785174],
       [0.88384157, 0.34993318],
       [1.13033101, 0.30044669]])

In [31]:
#common value of array 
a = np.array([1,2,3,4,5])
b = np.array([6,3,4,5])
c = np.intersect1d(a,b)
c

array([3, 4, 5])

In [35]:
a = np.linspace(0,1,12)
a

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [36]:
a = np.random.rand(10)
b = np.sort(a)
b

array([0.06072096, 0.31999982, 0.33322891, 0.37318176, 0.44207901,
       0.7740319 , 0.84047813, 0.94931101, 0.95294241, 0.98134497])

In [38]:
a = np.random.rand(10)
b = np.argmax(a)
a[b]=4
a

array([0.63438175, 0.14494566, 4.        , 0.51175123, 0.75298911,
       0.35355248, 0.6190247 , 0.12788976, 0.02419105, 0.28876986])

In [39]:
a = np.array([[10,20,30],[40,50,60]])
for i,v in np.ndenumerate(a):
    print(i,v)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(1, 0) 40
(1, 1) 50
(1, 2) 60


In [40]:
#swap rows of array 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[[0,2]]=a[[2,0]]
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [41]:
a = np.array([1.123456, 2.234567, 3.345678, 4.456789])
np.set_printoptions(precision=2)
a

array([1.12, 2.23, 3.35, 4.46])

In [42]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
c = np.cov(a,b)
c

array([[ 2.5, -2.5],
       [-2.5,  2.5]])

In [43]:
#chech df empty or not 
a = pd.DataFrame()
b = a.empty
b

True

In [44]:
#reindexing 
a = {'A': [1, 2, 3], 'B': [4, 5, 6]}
b = pd.DataFrame(a)
c = ['a','b','c']
d = b.reindex(c)
d

A   B
a NaN NaN
b NaN NaN
c NaN NaN

In [45]:
a = {'N':['A','B'],'L':['C','D']}
b = pd.DataFrame(a)
b

N  L
0  A  C
1  B  D

In [48]:
#from list 
a = [['A',25,26],['B',27,28]]
b = pd.DataFrame(a, columns=['XX','XXX','XXXX'])
b

XX  XXX  XXXX
0  A   25    26
1  B   27    28

In [ ]:
a = pd.read_csv(" ")

In [49]:
#df from array 
a = np.array([[2,5],[6,3]])
b = pd.DataFrame(a,columns=['A','B'])
b

A  B
0  2  5
1  6  3

In [52]:
a = pd.Series([1,2,3],name='A')
b = pd.Series([4,5,6],name='C')
c = pd.concat([a,b],axis=1)
c

A  C
0  1  4
1  2  5
2  3  6

In [53]:
a = pd.Series([1,2,3],name='A')
b = pd.Series([4,5,6],name='C')
c = pd.concat([a,b],axis=0)
c

0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64

In [54]:
data = [
    ['Alice', 25, 85],
    ['Bob', 30, 90],
    ['Charlie', 35, 95]]
b = pd.DataFrame(data, columns=['A','B','C'])
b

A   B   C
0    Alice  25  85
1      Bob  30  90
2  Charlie  35  95

In [55]:
#df from array 
a = np.arange(1,13).reshape(3,4)
b = pd.DataFrame(a)
b

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [56]:
#df from array 
a = np.arange(1,13).reshape(3,4)
b = pd.DataFrame(a,columns=['A','B','C','D'])
b

A   B   C   D
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [57]:
a = {
    'A': np.array([10,20]),
    'B': np.array([10,20]),
    'C': np.array([10,20])}

In [59]:
b = pd.DataFrame(a)
b

A   B   C
0  10  10  10
1  20  20  20

In [60]:
#copy of series 
a = pd.Series([1,2,3,4,5])
b = a.copy()
b

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [62]:
#add index 
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]})
df.set_index('B',inplace=True)
df

A
B   
4  1
5  2
6  3

In [63]:
df['C']=[7,8,9]
df

A  C
B      
4  1  7
5  2  8
6  3  9

In [64]:
#rename column 
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]})
df.rename(columns={'A':'BB','B':'CC'},inplace=True)
df

BB  CC
0   1   4
1   2   5
2   3   6

In [67]:
#rename index 
df.rename(index={0:'X',1:'XX',2:'XXX'},inplace=True)
df

BB  CC
X     1   4
XX    2   5
XXX   3   6

In [68]:
for i,v in df.iterrows():
    print(i,v)

X BB    1
CC    4
Name: X, dtype: int64
XX BB    2
CC    5
Name: XX, dtype: int64
XXX BB    3
CC    6
Name: XXX, dtype: int64


In [71]:
#apply function 
def process(a):
    return a['BB']+a['CC']

In [72]:
a = df.apply(process, axis=1)
a

X      5
XX     7
XXX    9
dtype: int64

In [73]:
#array to dataframe
a = df.to_numpy()
a

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int64)

In [74]:
#list to dataframe
b = df['BB'].tolist()
b

[1, 2, 3]

In [75]:
#convert all colummn to list 
a = df.values.flatten().tolist()
a

[1, 4, 2, 5, 3, 6]

In [80]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]},index=['a','b','c'])
df

A  B
a  1  4
b  2  5
c  3  6

In [81]:
df.shape

(3, 2)

In [82]:
#insert column at specific index 
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]})
df.insert(2,'XXX',[8,8,8])
df

A  B  XXX
0  1  4    8
1  2  5    8
2  3  6    8

In [83]:
#drop row 
df=df.drop(2)
df

A  B  XXX
0  1  4    8
1  2  5    8

In [84]:
df=df.drop('XXX',axis=1)
df

A  B
0  1  4
1  2  5

In [85]:
df=df.drop(['A','B'],axis=1)
df

Empty DataFrame
Columns: []
Index: [0, 1]

In [87]:
#sort dataframe 
df = pd.DataFrame({
    'A': [3, 2, 1],
    'B': [1, 2, 3]})
df

A  B
0  3  1
1  2  2
2  1  3

In [88]:
a = df.sort_values(by='A')
a

A  B
2  1  3
1  2  2
0  3  1

In [89]:
a = df.sort_values(by=['A','B'])
a

A  B
2  1  3
1  2  2
0  3  1

In [90]:
#sort index 
df.sort_index()
df

A  B
0  3  1
1  2  2
2  1  3

In [91]:
#drop duplicates rows 
df = pd.DataFrame({
    'A': [1, 2, 2, 3, 4],
    'B': [5, 6, 6, 7, 8]})
a = df.drop_duplicates()
a

A  B
0  1  5
1  2  6
3  3  7
4  4  8

In [93]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [1, 2, 3],  # Duplicate of column 'A'
    'D': [7, 8, 9]})
a = df.T.drop_duplicates().T
a

A  B  D
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
#fill Nan with mean 
data = {
    'A': [1, 2, np.nan, 4, np.nan, 6],
    'B': [7, 8, 9, 10, 11, 12]}
df = pd.DataFrame(data)
df['A'].fillna(df['A'].mean(),inplace=True)
df

In [95]:
data = {
    'Name': ['John', 'Alice', 'Bob', 'Eve', 'Michael'],
    'Age': [23, 30, 35, 29, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Score': [88, 92, 95, 85, 90]}
df = pd.DataFrame(data)

In [96]:
a = df.iloc[:2,:2]
a

Name  Age
0   John   23
1  Alice   30

In [97]:
df[['Name','Age']]

Name  Age
0     John   23
1    Alice   30
2      Bob   35
3      Eve   29
4  Michael   40

In [98]:
df.loc[[0,2]]

Name  Age      City  Score
0  John   23  New York     88
2   Bob   35   Chicago     95

In [99]:
df

Name  Age         City  Score
0     John   23     New York     88
1    Alice   30  Los Angeles     92
2      Bob   35      Chicago     95
3      Eve   29      Houston     85
4  Michael   40      Phoenix     90

In [100]:
df.iloc[0,2]

'New York'

In [101]:
df.iloc[[0,2]]

Name  Age      City  Score
0  John   23  New York     88
2   Bob   35   Chicago     95

In [102]:
df.loc[[0,2]]

Name  Age      City  Score
0  John   23  New York     88
2   Bob   35   Chicago     95

In [103]:
df

Name  Age         City  Score
0     John   23     New York     88
1    Alice   30  Los Angeles     92
2      Bob   35      Chicago     95
3      Eve   29      Houston     85
4  Michael   40      Phoenix     90

In [105]:
a = df.copy()

In [ ]:
df['Name','Age']=df['Name','Age'].fillna(100)
df

In [110]:
df['Name']=df['Name'].str.upper()
df

Name  Age         City  Score      new
0     JOHN   23     New York     88     JOHN
1    ALICE   30  Los Angeles     92    ALICE
2      BOB   35      Chicago     95      BOB
3      EVE   29      Houston     85      EVE
4  MICHAEL   40      Phoenix     90  MICHAEL

In [111]:
df['Name']=df['Name'].str.len()
df

Name  Age         City  Score      new
0     4   23     New York     88     JOHN
1     5   30  Los Angeles     92    ALICE
2     3   35      Chicago     95      BOB
3     3   29      Houston     85      EVE
4     7   40      Phoenix     90  MICHAEL