In [1]:
import numpy as np

In [2]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a = np.zeros(10)
a.nbytes

80

In [5]:
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.add(a,b)
d = np.subtract(a,b)
e = np.divide(a,b)
f = np.multiply(a,b)

In [13]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
a = np.arange(10)
b = np.flip(a)
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [17]:
b = np.array([[9, 8, 7, 6, 5], [4, 3, 2, 1, 0]])
b = np.flip(b)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
b = np.array([[9, 8, 7, 6, 5], [4, 3, 2, 1, 0]])
b = np.flip(b,axis=1)
b

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [19]:
b = np.array([[9, 8, 7, 6, 5], [4, 3, 2, 1, 0]])
b = np.flip(b,axis=0)
b

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [27]:
c = np.array([0, 1,5,4,6])
np.nonzero(c)

(array([1, 2, 3, 4], dtype=int64),)

In [29]:
b = np.array([[9, 8, 7], [6, 5,8], [4, 3, 2]])
e = np.linalg.det(b)
e

19.99999999999999

In [31]:
t = np.random.rand(3,3,3)
t

array([[[0.2427635 , 0.70830708, 0.61361605],
        [0.92323665, 0.4201532 , 0.93150233],
        [0.61100236, 0.13172383, 0.47942653]],

       [[0.04897625, 0.51402728, 0.13581954],
        [0.44629784, 0.62418375, 0.96780445],
        [0.47011042, 0.03485767, 0.14030404]],

       [[0.70729011, 0.01015487, 0.45568251],
        [0.91056648, 0.59962449, 0.77680491],
        [0.43066732, 0.10749398, 0.56745868]]])

In [32]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
a = np.random.rand(5,3)
b = np.random.rand(3,5)
c = np.dot(a,b)
c

array([[0.38469542, 0.49274761, 0.34740062, 0.35349006, 0.33871612],
       [0.33717442, 0.45447702, 0.31358548, 0.3074991 , 0.2286413 ],
       [0.57695505, 0.74626918, 0.54898744, 0.58342512, 0.53042005],
       [0.63911707, 0.84493947, 0.5350533 , 0.47089846, 0.38997281],
       [0.93888585, 1.19126523, 0.7929065 , 0.75518826, 0.77164506]])

In [37]:
a = np.array([1,2,3,4,5])
b = np.array([6,3,4,5])
c = np.intersect1d(a,b)
c

array([3, 4, 5])

In [38]:
a = np.random.rand(10)
b = np.sort(a)
b

array([0.19336782, 0.28596937, 0.36280827, 0.4568154 , 0.46662327,
       0.50219092, 0.76863223, 0.93297005, 0.96741028, 0.99952942])

In [39]:
a = np.random.rand(10)
b = np.random.rand(10)
c = np.array_equal(a,b)
c

False

In [41]:
a = np.random.rand(10)
b = np.argmax(a)
a[b] = 11
a

array([ 0.62736085,  0.54519361,  0.48410486,  0.08225105,  0.68404396,
        0.16430402, 11.        ,  0.14810208,  0.74898595,  0.72667316])

In [42]:
a = np.array([1,2,3,4,5,6,2,1,3,4,5,6,7,8,9,5,2])
b = np.where(a==2)
b

(array([ 1,  6, 16], dtype=int64),)

In [44]:
a = np.array([1,2,3])
for i,v in np.ndenumerate(a):
    print(i,v)

(0,) 1
(1,) 2
(2,) 3


In [46]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[[0,1]]=a[[1,0]]
a

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [48]:
from scipy import stats 
a = np.array([10, 20, 20, 30, 40, 50])
b = stats.mode(a)
b

ModeResult(mode=20, count=2)

In [50]:
a = np.array([1.58, 20, 2.88, 3.550, 40, 50])
np.set_printoptions(precision=2)
a

array([ 1.58, 20.  ,  2.88,  3.55, 40.  , 50.  ])

In [52]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(2,6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [53]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape((2,6))
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [58]:
a = np.random.rand(15)
b = a.reshape(5,3)
b

array([[0.73, 0.94, 0.09],
       [0.77, 0.68, 0.29],
       [0.33, 0.76, 0.86],
       [0.64, 0.29, 0.42],
       [0.96, 0.82, 0.1 ]])

In [62]:
a = np.random.rand(2,2,2,2)
b = a.reshape(4,4)
b

array([[0.1 , 0.18, 0.31, 0.87],
       [0.11, 0.33, 0.37, 0.63],
       [0.59, 0.16, 0.76, 0.71],
       [0.53, 0.22, 0.07, 0.24]])

In [63]:
import pandas as pd 

In [64]:
a = pd.Series([1,2,3], index=['a','b','c'])
a

a    1
b    2
c    3
dtype: int64