In [2]:
#sort list of tuple 
a = [(5,'A'),(2,'B'),(3,'D')]
b = sorted(a, key=lambda x:x[0])
b

[(2, 'B'), (3, 'D'), (5, 'A')]

In [3]:
# sort dict 
a = [
    {'A': 'D', 'Age': 25},
    {'B': 'E', 'Age': 63},
    {'C': 'F', 'Age': 20}]
b = sorted(a, key=lambda x:x['Age'])
b

[{'C': 'F', 'Age': 20}, {'A': 'D', 'Age': 25}, {'B': 'E', 'Age': 63}]

In [4]:
a = [
    {'Age': 25},
    {'Age': 63},
    {'Age': 20}]
b = sorted(a, key=lambda x:x['Age'])
b

[{'Age': 20}, {'Age': 25}, {'Age': 63}]

In [6]:
#cube using lambda 
a = [1,2,3,4,5]
b = list(map(lambda x:x**3,a))
b

[1, 8, 27, 64, 125]

In [7]:
#check string strated with 
a = lambda x,y:x[0]==y
a('Hello','H')

True

In [10]:
#check digit using lmabda 
a= lambda x: x.isdigit()
a('Mayur')

False

In [13]:
#fibonaccing using lambda 
a = lambda x:x if x<2 else a(x-1) + a(x-2)
for i in range(10):
    print(a(i))

0
1
1
2
3
5
8
13
21
34


In [17]:
#intersection of 2 list 
a = [1,2,3,4,5]
b = [4,5,6,1,2]
c = list(filter(lambda x:x in a,b))
c

[4, 5, 1, 2]

In [19]:
a = [1,2,3,4,5]
b = [4,5,6,1,2]
c = list(map(lambda x:x in a,b))
c

[True, True, False, True, True]

In [20]:
#rearrnage posistve & negative numbers 
a = [12,-7,-5,5,3,-10,6,-1]
b = sorted(a, key=lambda x: x>0)
b

[-7, -5, -10, -1, 12, 5, 3, 6]

In [22]:
#odd & even using lambda 
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b = list(filter(lambda x:x%2==0,a))
c = list(filter(lambda x:x%2!=0,a))
print(b)
print(c)

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


In [23]:
#add list using lambda 
a = [1,2,3]
b = [4,5,6]
c = list(map(lambda x,y: x+y,a,b))
c

[5, 7, 9]

In [26]:
a = [19,26,29,52,78,91,104,24,144,130,]
b = list(filter(lambda x: x%19==0 or x%13==0,a))
b

[19, 26, 52, 78, 91, 104, 130]

In [27]:
#finf palindrone using lambda 
a = ["radar", "python", "level", "hello", "madam"]
b = list(filter(lambda x: x==x[::-1],a))
b

['radar', 'level', 'madam']

In [28]:
c = list(filter(lambda x: x==x[::-1],a))
c

['radar', 'level', 'madam']

In [29]:
#multipy list by 2 
a = [1, 2, 3, 4, 5]
b = list(map(lambda x: x*2,a))
b

[2, 4, 6, 8, 10]

In [32]:
#sum of postitve & negative numbers using lambda 
a = [1, -2, 3, -4, 5, -6]
b = sum(filter(lambda x: x >0,a))
c = sum(filter(lambda x: x<0,a))
print(b)
print(c)

9
-12


In [34]:
#min and max len using lambda 
a = [[1, 2], [3, 4, 5], [6], [7, 8, 9, 10]]
b = max(a, key=lambda x: len(x))
c = min(a, key=lambda x: len(x))
print(b)
print(c)

[7, 8, 9, 10]
[6]


In [37]:
# sort list using lambda 
a = [1, 2, 3, 4, 5]
b = lambda x:x==sorted(x)
b(a)

True

In [38]:
a = [1, 2, 3, 4, 5, 6]
b = [2, 4, 6]
c = list(filter(lambda x: x not in b,a))
c

[1, 3, 5]

In [39]:
#convert string from tuple to int 
a = ('1', '2', '3', '4', '5')
b = tuple(map(lambda x: int(x),a))
b

(1, 2, 3, 4, 5)

In [42]:
a = [1, 2, 1, 3, 2, 1, 4, 3]
b = list(map(lambda x: (x, a.count(x)), set(a)))
b

[(1, 3), (2, 2), (3, 2), (4, 1)]

In [43]:
c = list(map(lambda x: (x,a.count(x)), set(a)))
c

[(1, 3), (2, 2), (3, 2), (4, 1)]

In [44]:
d = list(map(lambda x: (x,a.count(x)), set(a)))
d

[(1, 3), (2, 2), (3, 2), (4, 1)]

In [47]:
#add 3 list using lambda 
a = [1, 2, 3]
b = [4, 5, 6]
c = [7, 8, 9]
d = list(map(lambda x,y,z: x+y+z, a,b,c))
d

[12, 15, 18]

In [48]:
#listify string 
a = ['hello', 'world', 'python']
b = list(map(list,a))
b

[['h', 'e', 'l', 'l', 'o'],
 ['w', 'o', 'r', 'l', 'd'],
 ['p', 'y', 't', 'h', 'o', 'n']]

In [50]:
#sqaure using lambda 
a = [1, 2, 3, 4, 5]
b = list(map(lambda x: x**2,a))
b

[1, 4, 9, 16, 25]

In [51]:
#diff bw list using lambda 
a = [10, 20, 30, 40]
b = [1, 2, 3, 4]
c = list(map(lambda x,y: x+y,a,b))
d = list(map(lambda x,y: x-y,a,b))
print(c)
print(d)

[11, 22, 33, 44]
[9, 18, 27, 36]


In [52]:
#int to string 
a = [1, 2, 3, 4, 5]
b = list(map(str,a))
b

['1', '2', '3', '4', '5']

In [53]:
#sum of list 
a = [1, 2, 3, 4, 5]
b = sum(map(lambda x: x,a))
b

15

In [55]:
#count pair using lambda 
a = [1, 2, 3, 4, 5]
b = [3, 1, 4, 2, 5]
c = sum(map(lambda x: x in b,a))
c

5

In [56]:
a = ['apple', 'banana', 'cherry']
b = list(map(str,a))
b

['apple', 'banana', 'cherry']

In [57]:
a = ['apple', 'banana', 'cherry']
b = list(map(lambda x: list(x),a))
b

[['a', 'p', 'p', 'l', 'e'],
 ['b', 'a', 'n', 'a', 'n', 'a'],
 ['c', 'h', 'e', 'r', 'r', 'y']]

In [58]:
a = [('a', 'b', 'c'), ('d', 'e', 'f'), ('g', 'h', 'i')]
b = list(map(lambda x: ''.join(x),a))
b

['abc', 'def', 'ghi']

In [61]:
a = [1, 2, 3, 4, 5]
b = [4, 5, 6, 7]
c = list(filter(lambda x: x not in b,a))
c

[1, 2, 3]

In [62]:
a = [1, 2, 3, 4, 5]
b = [4, 5, 6, 7]
c = list(filter(lambda x: x in b,a))
c

[4, 5]

In [63]:
#filter odd numbers 
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b = list(filter(lambda x: x%2!=0,a))
b

[1, 3, 5, 7, 9]

In [64]:
#filter non vovels 
a = ['a', 'b', 'c', 'e', 'i', 'o', 'u', 'x', 'y', 'z']
b = {'a', 'e', 'i', 'o', 'u'}
c = list(filter(lambda x:x in b,a))
c

['a', 'e', 'i', 'o', 'u']

In [ ]:
#Assignment 8

In [ ]:
with open(filename,'r') as file:
    a = file.read()
print(a)

In [ ]:
#read n lines of file 
with open(filename,'r') as file:
    for i in range(5):
        a = file.readlines()
        if not a:
            break
        print(a,end='')

In [ ]:
with open(filename,'a') as file:
    file.write('---'+ '\n')
with open(filename,'r') as file:
    new=file.read()
print(new)

In [ ]:
#read list lines of file 
with open(filename,'r') as file:
    new = file.readlines()
    last = new[-n:]
    for i in last:
        print(new,end='')

In [ ]:
#read line by line & store in list 
with open(filename,'r') as file:
    new = file.readlines()
    final = [i.strip() for i in new]
    print(final)

In [ ]:
#count number of lines 
with open(filename,'r') as file:
    new = file.readlines()
    final = len(new)
    print(final)

In [ ]:
#frequence of words in file 
from collections import Counter 
with open(filename,'r') as file:
    new = file.read().lower().split()
    final = dict(Counter(new))
    print(final)

In [ ]:
#copy content of 1 file to another 
with open(filename,'r') as file:
    new = file.read()
with open(ffilename,'w') as ffile:
    ffile.write(new)
    print(new)

In [65]:
#check leap year 
def leap(year):
    return (year%4==0 and year%100!=0) or (year%400==0)

In [67]:
from datetime import datetime 
a = "Jan 1 2014 2:43PM"
b = a.strftime("%Y-%m-%d %H:%M:%S")
b

AttributeError: 'str' object has no attribute 'strftime'

In [70]:
from datetime import datetime, timedelta
a = datetime.now()
b = a - timedelta(days=5)
b

datetime.datetime(2024, 10, 12, 20, 46, 24, 644008)

In [71]:
#net 5 days 
a = datetime.now()
for i in range(5):
    nextd = a + timedelta(days=i)
    print(nextd.date())

2024-10-17
2024-10-18
2024-10-19
2024-10-20
2024-10-21


In [ ]:
#select all sundays of specefied year
import calendar
y=2024
for month in range(1,13):
    for week in calendar.monthcalendar(y,month):
        if week[6]!=0:
            print(week[6])

In [ ]:
import os
original = 'example.txt' 
new = 'renamed_example.txt'
with open(filename,'r') as file:
    file.write('----')
os.rename(original,new)

In [76]:
import os 

In [78]:
a = os.listdir()
print(a)

['.ipynb_checkpoints', '10 Oct.ipynb', '11 Oct.ipynb', '13 Oct.ipynb', '14 Oct.ipynb', '15 Oct.ipynb', '16 Oct.ipynb', '17 Oct.ipynb', '9 Oct 2024.ipynb', 'aa.csv', 'abcd.json', 'Action_movies.csv', 'bank-additional-full.csv', 'created_data.csv', 'data.csv', 'Emp_Records.xlsx', 'Emp_Records_1.csv', 'Emp_Records_1.xlsx', 'Emp_Records_csv.csv', 'Final', 'mayur.xlsx', 'movies_data.csv', 'movies_details.xlsx', 'New_created_data.xlsx', 'output_data.csv', 'output_data.xlsx', 'test.csv', 'titanic.csv', 'Untitled.ipynb']


In [ ]:
b = os.listdir(path)
b

In [ ]:
# Assignment 11

In [1]:
import numpy as np
import pandas as pd 

In [4]:
a = np.zeros(3)
b = pd.DataFrame(a)
b

0
0  0.0
1  0.0
2  0.0

In [5]:
a = np.zeros(5)
a[0]=55
a

array([55.,  0.,  0.,  0.,  0.])

In [12]:
a = np.arange(55,100).reshape(5,9)
b = pd.DataFrame(a,columns=['A','B','C','D','E','F','G','I','K'])
b

A   B   C   D   E   F   G   I   K
0  55  56  57  58  59  60  61  62  63
1  64  65  66  67  68  69  70  71  72
2  73  74  75  76  77  78  79  80  81
3  82  83  84  85  86  87  88  89  90
4  91  92  93  94  95  96  97  98  99

In [14]:
b.set_index('A',inplace=True)

In [15]:
b

B   C   D   E   F   G   I   K
A                                 
55  56  57  58  59  60  61  62  63
64  65  66  67  68  69  70  71  72
73  74  75  76  77  78  79  80  81
82  83  84  85  86  87  88  89  90
91  92  93  94  95  96  97  98  99

In [16]:
b.reset_index()

A   B   C   D   E   F   G   I   K
0  55  56  57  58  59  60  61  62  63
1  64  65  66  67  68  69  70  71  72
2  73  74  75  76  77  78  79  80  81
3  82  83  84  85  86  87  88  89  90
4  91  92  93  94  95  96  97  98  99

In [18]:
a= np.array([1,2,3])
b =a[::-1]
b

array([3, 2, 1])

In [19]:
a = np.array([3.14, 2.71, 7.65, 5.49, 1.23])
b = np.round(a)
b

array([3., 3., 8., 5., 1.])

In [20]:
a = np.array([3.14, 2.71, 7.65, 5.49, 1.23])
b = np.ceil(a)
b

array([4., 3., 8., 6., 2.])

In [21]:
a = np.array([3.14, 2.71, 7.65, 5.49, 1.23])
b = np.floor(a)
b

array([3., 2., 7., 5., 1.])

In [25]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.mean(a, axis=0)
c = np.mean(a, axis=1)
print(b)
print(c)

[4. 5. 6.]
[2. 5. 8.]


In [26]:
a = np.array([0, 30, 45, 60, 90, 180, 270, 360])
b = np.rad2deg(a)
c = np.deg2rad(a)
print(b)
print(c)

[    0.          1718.87338539  2578.31007809  3437.74677078
  5156.62015618 10313.24031235 15469.86046853 20626.48062471]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265
 4.71238898 6.28318531]


In [29]:
a = np.arange(10).reshape(5,2)
b = pd.DataFrame(a, columns=['A','B'])
b

A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [30]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
b = np.flip(a)
b

array([[9, 8],
       [7, 6],
       [5, 4],
       [3, 2],
       [1, 0]])

In [32]:
b = np.flip(a, axis=0)
b

array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

In [33]:
b = np.flip(a, axis=1)
b

array([[1, 0],
       [3, 2],
       [5, 4],
       [7, 6],
       [9, 8]])

In [35]:
a = np.array([1, 2, 0, 0, 4, 0])
b = np.nonzero(a)
b

(array([0, 1, 4], dtype=int64),)

In [36]:
a = np.array([1, 2, 0, 0, 4, 0])
for i,v in np.ndenumerate(a):
    print(i,v)

(0,) 1
(1,) 2
(2,) 0
(3,) 0
(4,) 4
(5,) 0


In [37]:
from scipy import stats 
a = np.array([1, 2, 0, 0, 4, 0])
b = stats.mode(a)
b

ModeResult(mode=0, count=3)

In [39]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
a = np.zeros(3,3)
a

TypeError: Cannot interpret '3' as a data type

In [41]:
# Assignment 12

In [42]:
a = pd.Series([1,2,3,4,5,6])
a

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [43]:
a = {'A': [1, 2, 3], 'B': [4, 5, 6]}
b = pd.DataFrame(a)
c = b.reindex(['a','b','c'])
c

A   B
a NaN NaN
b NaN NaN
c NaN NaN

In [44]:
a = {'Name': ['Alice', 'Bob', 'Charlie'], 
        'Age': [25, 30, 35]}
df = pd.DataFrame(a)
df

Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [45]:
a = [
    ['Alice', 25, 85],
    ['Bob', 30, 90],
    ['Charlie', 35, 95]]
b = pd.DataFrame(a, columns=['a','b','c'])
b

a   b   c
0    Alice  25  85
1      Bob  30  90
2  Charlie  35  95

In [47]:
a = np.random.rand(5,5)
b = pd.DataFrame(a, columns=['A','B','C','D','E'])
b

A         B         C         D         E
0  0.907541  0.589674  0.963870  0.960022  0.397503
1  0.844913  0.998541  0.463374  0.808775  0.761463
2  0.988869  0.009326  0.441388  0.621954  0.956088
3  0.121119  0.330795  0.288235  0.691055  0.628705
4  0.045803  0.971249  0.815916  0.941882  0.052315

In [53]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]},index=['a','b','c'])

In [54]:
df

A  B
a  1  4
b  2  5
c  3  6

In [55]:
df['C']=5

In [56]:
df

A  B  C
a  1  4  5
b  2  5  5
c  3  6  5

In [58]:
df.insert(3,'D',8)

In [59]:
df

A  B  C  D
a  1  4  5  8
b  2  5  5  8
c  3  6  5  8

In [62]:
df.drop('A',axis=1,inplace=True)
df

B  C  D
a  4  5  8
b  5  5  8
c  6  5  8

In [63]:
df.quantile(0.25)

B    4.5
C    5.0
D    8.0
Name: 0.25, dtype: float64

In [64]:
df['B'].quantile(0.25)

4.5

In [67]:
df.sort_values(by='B')

B  C  D
a  4  5  8
b  5  5  8
c  6  5  8

In [68]:
df.drop_duplicates(subset=['D'])

B  C  D
a  4  5  8

In [69]:
df.T.drop_duplicates().T

B  C  D
a  4  5  8
b  5  5  8
c  6  5  8

In [74]:
df['E'] = 0

In [75]:
df

B  C  D  E
a  4  5  8  0
b  5  5  8  0
c  6  5  8  0

In [78]:
df.fillna(df['E'].mean(), inplace=True)

In [79]:
df

B  C  D  E
a  4  5  8  0
b  5  5  8  0
c  6  5  8  0

In [80]:
data = {
    'A': [1, 2, np.nan, 4, np.nan, 6],
    'B': [7, 8, 9, 10, 11, 12]}
df = pd.DataFrame(data)

In [81]:
df.fillna(df['A'].mean(), inplace=True)
df

A   B
0  1.00   7
1  2.00   8
2  3.25   9
3  4.00  10
4  3.25  11
5  6.00  12

In [82]:
df['A'].mean()

3.25