In [1]:
import numpy as np

In [5]:
#ndim is a way to find out how many dimensions an array has.
#Think of dimensions like layers or levels of data.
a = np.array(7.28)
print(a.ndim)

0


In [6]:
a = np.array([7.28])
print(a.ndim)

1


In [7]:
a = np.array([[7.28]])
print(a.ndim)

2


In [8]:
a = np.array([[[7.28]]])
print(a.ndim)

3


In [ ]:
# shape of an array tells you the size of each dimension.
#You can think of it like the dimensions of a room: 
#it tells you how long, wide, and high it is.

In [9]:
a = np.array(7.28)
print(a.shape)

()


In [10]:
a = np.array([7.28])
print(a.shape)

(1,)


In [11]:
a = np.array([[7.28]])
print(a.shape)

(1, 1)


In [12]:
a = np.array([[[7.28]]])
print(a.shape)

(1, 1, 1)


In [13]:
#indexing on 2d Array
a = np.array([[4,5],[9,1],[7,4]])
a

array([[4, 5],
       [9, 1],
       [7, 4]])

In [14]:
a[0]

array([4, 5])

In [17]:
a[0][1]

5

In [27]:
#slicing 
a = np.array([[4,5],[9,1],[7,4]])

In [28]:
a[:,:2]

array([[4, 5],
       [9, 1],
       [7, 4]])

In [29]:
a[:,1]

array([5, 1, 4])

In [31]:
print(a.ndim)
print(a.shape)

2
(3, 2)


In [35]:
#convert to ndim array 
a = np.array([1,2,3], ndmin=3)
a

array([[[1, 2, 3]]])

In [37]:
b = np.array([[1,2],[2,3],[4,5]])
b.shape

(3, 2)

In [39]:
b = np.array([[1,2],[2,3],[4,5]], ndmin=4)
b

array([[[[1, 2],
         [2, 3],
         [4, 5]]]])

In [43]:
a = np.array([1,2,3,4])

In [52]:
b = a.reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [56]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
c = c.reshape(2,5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
c = c.reshape(5,2)
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [62]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
c = c.reshape(10,1)
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [66]:
#flatten list
a = np.array([[1,2,3,4],[5,6,10,20],[30,40,50,60]])
a.reshape(12)

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30, 40, 50, 60])

In [71]:
a = np.array([[1,2,3,4],[5,6,10,20],[30,40,50,60]])
print(a.shape)

(3, 4)


In [72]:
a = np.array([[1,2,3,4],[5,6,10,20],[30,40,50,60]])
b = a.reshape(12,)

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30, 40, 50, 60])

In [74]:
b.shape

(2, 2)

In [77]:
a = np.array([[1,2,3,4],[5,6,10,20],[30,40,50,60]])
b = a.reshape(-1)
b

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30, 40, 50, 60])

In [79]:
c = b.tolist()
c

[1, 2, 3, 4, 5, 6, 10, 20, 30, 40, 50, 60]

In [80]:
d = np.array([1,2,3,4,5])
e = d**2
e

array([ 1,  4,  9, 16, 25])

In [82]:
d = np.array([1,2,3,4,5])
e = d**3
e

array([  1,   8,  27,  64, 125], dtype=int32)

In [84]:
r = np.zeros(10, dtype='int')
r

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
r = np.zeros(10)
r

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
r = np.ones(10)
r

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [87]:
t = np.arange(2,10)
t

array([2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
#linespace
t = np.linspace(1,50,num=10,dtype='int')
t

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [93]:
a =np.array([ 99,1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [94]:
np.sort(a)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50, 99])

In [95]:
np.sort(a, axis=0)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50, 99])