In [2]:
import numpy as np

In [6]:
#1d array into 2d array 
a = np.array([1,2,3,], ndmin=2)
a

array([[1, 2, 3]])

In [13]:
#reshape
a = np.array([1,2,3,4,5,6])
b = a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
#flatten list 
a = np.array([[1,2,3,4],[5,6,10,20],[30,40,50,60]])
b = a.reshape(-1)
b

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30, 40, 50, 60])

In [16]:
a =np.array([3,4,5,6,7])
b = a**2
b

array([ 9, 16, 25, 36, 49])

In [19]:
# multi 
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.multiply(a,b)
c

array([ 4, 10, 18])

In [21]:
#np.zeroz 
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [22]:
a = np.zeros([3,3])
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#np.ones
a = np.ones(5, dtype= float)
a

array([1., 1., 1., 1., 1.])

In [24]:
a = np.ones([5,5], dtype= float)
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
#np.arange
a = np.arange(5,25)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [27]:
#linespace
a = np.linspace(5,25, num=5)
a

array([ 5., 10., 15., 20., 25.])

In [28]:
#eye 
a = np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [29]:
#identify
a = np.identity(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
#random 
a = np.random.rand(5)
a

array([0.90191724, 0.90590407, 0.02012176, 0.75565638, 0.69760996])

In [32]:
a = np.random.randint(5,10, size=5)
a

array([9, 7, 8, 5, 6])

In [36]:
a = np.random.randint(5,10, size=5)
''.join([str(i) for i in list(a)])

'86576'

In [37]:
a = np.random.randn(5)
a

array([-0.287861  ,  0.32142799,  0.63665244,  0.2912567 , -1.12192049])

In [38]:
a = np.random.ranf(5)
a

array([0.44342088, 0.77918333, 0.52286701, 0.39423324, 0.37913793])

In [44]:
#sort
a = np.array([50,44,1,2,3,4,5,6,7,8,9])
np.sort(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 44, 50])

In [47]:
a = np.array([[11,2,3],[4,5,6]])
np.sort(a, axis=0)

array([[ 4,  2,  3],
       [11,  5,  6]])

In [48]:
a = np.array([[11,2,3],[4,5,6]])
np.sort(a, axis=1)

array([[ 2,  3, 11],
       [ 4,  5,  6]])

In [49]:
a = np.array([1,2,3,4,5])
b = np.mean(a)
b

3.0

In [51]:
#median
a = np.array([1,2,3,4,5,8,9,])
b = np.median(a)
b

4.0

In [53]:
from scipy import stats

In [55]:
a = np.array([1,2,3,8,4,5,8,9,])
b = stats.mode(a)
b

ModeResult(mode=8, count=2)

In [63]:
#liner algerba 
a = np.array([[1,2],[4,5]])
np.linalg.inv(a)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [65]:
a = np.log(1)
a

0.0

In [68]:
a = np.log(2)
a

0.6931471805599453

In [69]:
a = np.log10(2)
a

0.3010299956639812

In [72]:
a = np.array([[1,24,5]])
b = np.log(a)
b

array([[0.        , 3.17805383, 1.60943791]])

In [73]:
#degree to radiant
a = np.array([1,2,3,4,5])
b = np.rad2deg(a)
b

array([ 57.29577951, 114.59155903, 171.88733854, 229.18311805,
       286.47889757])

In [74]:
a = np.array([1,2,3,4,5])
b = np.deg2rad(a)
b

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646])

In [75]:
a = np.array([1,2,3,4,5])
for i in np.nditer(a):
    print(i)

1
2
3
4
5


In [76]:
a = np.array([1,2,3,4,5])
np.min(a)

1

In [79]:
a = np.array([[[2,3,4],[5,6,7],[8,9,10]], [[12,13,14],[15,16,17],[18,19,110]]])
a.flatten()

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  13,  14,  15,
        16,  17,  18,  19, 110])

# Assignment 6

In [1]:
#largest prime factor of number
def large(n):
    i=2
    while i*i <=n:
        if n%i:
            i += 1
        else:
            n//=i
    return n

In [2]:
#unique prime factors of number 
def pmu(n):
    f = []
    while i*i<=n:
        if n%i:
            i+= 1
        else:
            n//i
            f.appened(i)
    if n>1:
        f.append(n)
    return f 

In [3]:
#factorial
n=5
f=1
for i in range(1,n+1):
    f = f * i
print(f)

120


In [4]:
#sum of odd factors
def odf(n):
    t_s = 0
    for i in range(1,n+1):
        if n%i==0 and i%2!=0:
            t_s += i
    return t_s

In [5]:
def enf(n):
    t = 0
    for i in range(1,n+1):
        if n%i==0 and i%2==0:
            t += i
    return t

In [6]:
#chech binanary representation is palindrome 
def palin(n):
    binr = bin(n)[2:]
    return binr==binr[::-1]

In [8]:
#common divisors of 2 numbers 
def common(a,b):
    minn = min(a,b)
    c =[]
    for i in range(1,minn+1):
        if a%i==0 and b%i==0:
            c.append(i)
    return c

In [9]:
common(2,5)

[1]

In [10]:
#check if count of divisor is odd or even 
def c_d(n):
    c = 0
    for i in range(1,n+1):
        if n%i==0:
            c += 1
    if c%2==0:
        print('even')
    else:
        print('odd')

In [11]:
c_d(5)

even


In [13]:
#diff b/w odd and even digits 
a = [1,2,3,4,5,6,7,8,9,10]
od = []
ev = []
for i in a:
    if i%2==0:
        ev.append(i)
    else:
        od.append(i)
sum_od = sum(od)
sum_ev = sum(ev)
final = sum_ev-sum_od
final

5

In [21]:
#most occuring char in string 
from collections import Counter
a = "Mayur Gohane"
b = Counter(a)
c = b.most_common(1)
c

[('a', 2)]

In [22]:
#sum of even factors
def c_e(n):
    c = 0
    for i in range(1,n+1):
        if n%i==0 and i%2==0:
            c +=i
    return c

In [23]:
#check if all digits of number divide it 
def divide(n):
    for i in str(n):
        if i==0 or n%int(i)!=0:
            return False
    return True  

In [ ]:
#copy odd lines from file
o = []
with open(filename,'r') as file:
    for i,v in enumerate(file):
        if i%2!=0:
            c.append(v.strip())
return ''.join(o)

In [33]:
#replace whitespace & underscore 
a = "Mayur gohane_r"
b = a.replace(' ','_').replace('_','temp').replace(' ','_').replace('temp',' ')
b

'Mayur gohane r'

In [38]:
#yy-mm-dd to dd-mm-yy
d = "23-09-06"
yy,mm,dd=d.split('-')
c = f"{dd}-{mm}-{yy}"
c

'06-09-23'

In [40]:
#count a & e
from collections import Counter
a = "masyur gohaner a i "
b = Counter(a)
b

Counter({' ': 4,
         'a': 3,
         'r': 2,
         'm': 1,
         's': 1,
         'y': 1,
         'u': 1,
         'g': 1,
         'o': 1,
         'h': 1,
         'n': 1,
         'e': 1,
         'i': 1})

In [42]:
#check list sorted using lambda 
a = [8,7441,23,34,12,2]
b = lambda x:x==sorted(x)
b(a)

False

In [50]:
#convert given list of intgers & tuple ot integers in a list of string
a = [1,2]
b = (3,4)
c = list(map(str,a))
d = list(map(str,b))
final = c+d
print(final)

['1', '2', '3', '4']


# Assignment 11 

In [52]:
import numpy as np

In [55]:
#vector of zero 
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
#memoroy size of array
a = np.zeros(10)
b = a.nbytes
b

80

In [60]:
#null vector of size 10 but the fifth value which is 1
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [61]:
#vector with values ranging from 15 to 45
a = np.arange(15,45)
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [62]:
#Reverse a vector
a = np.array([1,2,3,4,5])
a[::-1]

array([5, 4, 3, 2, 1])

In [63]:
#add, subtract, multiply, divide arguments element-wise
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
sub = np.subtract(a,b)
mult = np.multiply(a,b)
div = np.divide(a,b)
print(sub,mult,div)

[-4 -4 -4 -4] [ 5 12 21 32] [0.2        0.33333333 0.42857143 0.5       ]


In [64]:
#round elements of the array to the nearest integer
a = np.array([3.14, 2.71, 7.65, 5.49, 1.23])
b = np.round(a)
b

array([3., 3., 8., 5., 1.])

In [65]:
#floor and ceiling values of the elements
a = np.array([3.14, 2.71, 7.65, 5.49, 1.23])
b = np.ceil(a)
c = np.array(b)
print(b,c)

[4. 3. 8. 6. 2.] [4. 3. 8. 6. 2.]


In [71]:
# mean across dimensions, in a 2D NumPy array.
a = np.array([[8, 2], [7441, 12], [23, 34], [34, 5], [12, 1], [2, 10]])
m_r = np.mean(a, axis=0) #column
m_c = np.mean(a, axis=1) #row
print(m_r,m_c)

[1253.33333333   10.66666667] [   5.  3726.5   28.5   19.5    6.5    6. ]


In [72]:
# degrees to radians
a = np.array([0, 30, 45, 60, 90, 180, 270, 360])
b = np.deg2rad(a)
b

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       3.14159265, 4.71238898, 6.28318531])

In [73]:
a = np.array([0, 30, 45, 60, 90, 180, 270, 360])
b = np.rad2deg(a)
b

array([    0.        ,  1718.87338539,  2578.31007809,  3437.74677078,
        5156.62015618, 10313.24031235, 15469.86046853, 20626.48062471])

In [75]:
#3x3 matrix with values ranging from 0 to 8
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
#reverse the columns of a 2D array
a = np.array([[2,1,0],[5,4,3],[8,7,6]])
b = np.flip(a, axis=0)
b

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [77]:
a = np.array([[2,1,0],[5,4,3],[8,7,6]])
b = np.flip(a, axis=1)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
a = np.array([1, 2, 0, 0, 4, 0])
b = np.nonzero(a)[0]
b

array([0, 1, 4], dtype=int64)

In [79]:
#determinant of an array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.linalg.det(a)
b

0.0

In [82]:
#inverse of a given matrix
a = np.array([[1,2,3],[0,4,1],[7,8,9]])
b = np.linalg.inv(a)
b

array([[-0.66666667, -0.14285714,  0.23809524],
       [-0.16666667,  0.28571429,  0.02380952],
       [ 0.66666667, -0.14285714, -0.0952381 ]])

In [86]:
#random vector of size 30 and find the mean value
a = np.random.rand(30)
b = np.mean(a)
b

0.5308022286955711

In [88]:
# extract all numbers between a given range
a = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])
up = 40
lo = 30
c = a[(a>=lo) & (a<= up)]
c

array([30, 35, 40])

In [89]:
#3x3x3 array with random values
a = np.random.rand(30)
a

array([0.03413383, 0.35064288, 0.65025122, 0.93707532, 0.19019864,
       0.99928927, 0.10854056, 0.10892917, 0.43736194, 0.80880918,
       0.01686827, 0.28945856, 0.31411092, 0.64802575, 0.83709861,
       0.8444271 , 0.2199541 , 0.94594839, 0.31851563, 0.76199384,
       0.15788051, 0.95379003, 0.1878714 , 0.83079881, 0.043983  ,
       0.93128092, 0.55792437, 0.50964103, 0.69287486, 0.14119696])

In [93]:
# 10x10 array with random values and find the minimum and maximum values
a = np.random.rand(10,10)
minn = np.mean(a)
maxx = np.max(a)
print(minn,maxx)

0.4533378202812586 0.9919789548756905


In [97]:
# Create a 2d array with 1 on the border and 0 inside
a = np.ones((5,5))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#5x5 matrix with values 1,2,3,4 just below the diagonal

In [101]:
a = np.zeros((5,5))
np.fill_diagonal(a[1:],[1,2,3,4])
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [102]:
#Create a 3x3 identity matrix
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#8x8 matrix and fill it with a checkerboard pattern

In [104]:
a = np.tile([[0,1],[1,0]],(4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [107]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.random.rand(5,3)
b = np.random.rand(3,2)
c = np.dot(a,b)
c

array([[0.48204336, 1.23091767],
       [0.22209471, 0.85424407],
       [0.17452212, 1.0118257 ],
       [0.39047103, 0.75684642],
       [0.49695268, 1.35232005]])

In [108]:
# 1D array, negate all elements which are between 3 and 8, in place
a = np.array([1,2,3,4,5,6,7,8,9,10,11])
a[(a>=3) & (a<=8)]
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [109]:
#How to round away from zero a float array?
a = np.array([1.2,2.5,-3.7,-4.2])
b = np.where(a >0, np.ceil(a), np.floor(a))
b

array([ 2.,  3., -4., -5.])

In [110]:
#How to find common values between the two arrays?
a = np.array([1,2,3,4,5])
b = np.array([6,3,4,5])
c = np.intersect1d(a,b)
c

array([3, 4, 5])

In [112]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded
a = np.linspace(0,1,12)[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [113]:
#random vector of size 10 and sort it
a = np.random.rand(10)
b = np.sort(a)
b

array([0.01221485, 0.16695237, 0.19473559, 0.2002271 , 0.23660545,
       0.35053485, 0.73965822, 0.81127223, 0.81432157, 0.83862174])

In [117]:
#Create a 5x5 matrix with row values ranging from 0 to 4
a = np.tile(np.arange(5),(5,1))
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [118]:
#two random arrays A and B, check if they are equal
a = np.random.rand(10)
b = np.random.rand(10)
c = np.array_equal(a,b)
c

False

In [124]:
# random vector of size 10 and replace the maximum value by 0
a = np.random.rand(10)
b = np.argmax(a)
a[b]=0
a

array([0.54238789, 0.93301323, 0.        , 0.36947594, 0.31964932,
       0.90361399, 0.56359284, 0.01031073, 0.12788198, 0.22333033])

In [125]:
#How to find out multiple indices of an item?
a = np.array([1,2,3,4,5,6,2,1,3])
b = np.where(a==1)
b

(array([0, 7], dtype=int64),)

In [126]:
# enumerate
a = np.array([[10,20,30],[40,50,60]])
for i,v in np.ndenumerate(a):
    print(i,v)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(1, 0) 40
(1, 1) 50
(1, 2) 60


In [ ]:
#How to sort an array by the nth column?

In [127]:
a = np.array([[10,12,13],[4,5,6],[7,8,9]])
b = a[a[:,1].argsort()]
b

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])

In [128]:
#How to swap two rows of an array?
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[[0,2]]=a[[2,0]]
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [132]:
#compute the mean of a NumPy array
a =np.array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])
all_mean = np.mean(a)
mean_row = np.mean(a, axis=1)
mans_col = np.mean(a, axis=0)

In [133]:
#median
a =np.array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])
b = np.median(a)
b

5.0

In [134]:
#standard deviation
a =np.array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])
b = np.std(a)
b

2.581988897471611

In [135]:
#mode
from scipy import stats 
a =np.array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])
b = stats.mode(a)
b

ModeResult(mode=array([1, 2, 3], dtype=int64), count=array([1, 1, 1], dtype=int64))

In [139]:
#print only 3 decimal places
a = np.array([1.123456, 2.234567, 3.345678, 4.456789])
np.set_printoptions(precision=2)
a

array([1.12, 2.23, 3.35, 4.46])

In [140]:
# inverse of a given matrix
a = np.array([[1, 2, 3],[0, 1, 4],[5, 6, 0]])
b = np.linalg.inv(a)
b

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [141]:
#covariance matrix of two given arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
c = np.cov(a,b)
c

array([[ 2.5, -2.5],
       [-2.5,  2.5]])

In [143]:
#most frequent value
from collections import Counter
a = np.array([1, 2, 2, 3, 4, 4, 4, 5])
b = dict(Counter(a))
b

{1: 1, 2: 2, 3: 1, 4: 3, 5: 1}

In [144]:
from scipy import stats
a = np.array([1, 2, 2, 3, 4, 4, 4, 5])
b = stats.mode(a)
b

ModeResult(mode=4, count=3)

In [150]:
#1D array to 3D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape((2,3,2))
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [152]:
#4D array to 2D array
a = np.random.rand(2,3,4,5)
b = a.reshape(6,20)
b

array([[0.06, 0.82, 0.4 , 0.23, 0.93, 0.09, 0.86, 0.56, 0.22, 0.13, 0.43,
        0.55, 0.58, 0.69, 0.11, 0.36, 0.59, 0.8 , 0.68, 0.23],
       [0.82, 0.09, 0.59, 0.04, 0.55, 0.45, 0.71, 0.48, 0.01, 0.73, 0.47,
        0.51, 0.14, 0.09, 0.04, 0.23, 0.8 , 0.61, 0.1 , 0.25],
       [0.47, 0.42, 0.3 , 0.5 , 0.97, 0.39, 0.99, 0.57, 0.24, 0.9 , 0.06,
        0.17, 0.38, 0.35, 0.87, 0.13, 0.26, 0.56, 0.58, 0.01],
       [0.52, 0.27, 0.11, 0.63, 0.85, 0.67, 0.02, 0.13, 0.84, 0.55, 0.68,
        0.1 , 0.33, 0.05, 0.18, 0.36, 0.76, 0.33, 0.26, 0.43],
       [0.71, 0.2 , 0.35, 0.21, 0.45, 0.25, 0.67, 0.71, 0.04, 0.76, 0.94,
        0.72, 0.45, 0.57, 0.67, 0.17, 0.48, 0.98, 0.45, 0.32],
       [0.41, 0.44, 0.09, 0.45, 0.23, 0.29, 0.56, 0.61, 0.52, 0.51, 0.5 ,
        0.44, 0.72, 0.46, 0.32, 0.34, 0.73, 0.36, 0.09, 0.94]])

In [153]:
#array filled with all zeros
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [154]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [155]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [156]:
#Find the number of rows and columns of a given matrix
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
r,c = a.shape
print(r,c)

3 3
