In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
print(a.shape)

(5,)


In [5]:
a[2]

3

In [6]:
a[4]

5

In [7]:
a[-1]

5

In [8]:
b = np.sum(a)
b

15

In [9]:
a = np.array([])
a

array([], dtype=float64)

In [10]:
a = np.zeros(20)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [12]:
b = n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [14]:
np.nbytes(a)

TypeError: '_typedict' object is not callable

In [16]:
a.nbytes

160

In [17]:
b = np.random.rand(10,45)
b

array([[0.80299084, 0.64491786, 0.98758166, 0.17817298, 0.02153146,
        0.6311936 , 0.83123012, 0.81309017, 0.43140199, 0.58460627,
        0.32283052, 0.34794096, 0.88479479, 0.86078248, 0.32161881,
        0.8591462 , 0.06297217, 0.52374801, 0.59840717, 0.57214573,
        0.41584333, 0.83841493, 0.08444519, 0.2821446 , 0.77395994,
        0.6811554 , 0.82316566, 0.64275741, 0.58832448, 0.40392847,
        0.51896462, 0.32849456, 0.5992877 , 0.19803216, 0.38169642,
        0.10654514, 0.05300233, 0.12322578, 0.1129645 , 0.5842339 ,
        0.25089555, 0.30754491, 0.94616112, 0.35747962, 0.32616535],
       [0.76453363, 0.18770779, 0.58238272, 0.51545286, 0.9115219 ,
        0.24926631, 0.80331182, 0.92457567, 0.99121572, 0.40262408,
        0.80356284, 0.63634906, 0.56038521, 0.35587782, 0.17115247,
        0.07717931, 0.99827089, 0.3742399 , 0.23407113, 0.62648502,
        0.50833609, 0.81520703, 0.83892073, 0.85188889, 0.43760505,
        0.55453263, 0.87610607, 0.16720306, 0.9

In [20]:
c = np.flip(b)
c

array([[0.31687284, 0.11377441, 0.7901206 , 0.90687756, 0.25139021,
        0.30748721, 0.15352615, 0.70349131, 0.90283227, 0.82463731,
        0.44380126, 0.37062972, 0.75235967, 0.76458839, 0.40814953,
        0.15299047, 0.30101921, 0.806312  , 0.2274656 , 0.9646393 ,
        0.21737581, 0.29331419, 0.60110283, 0.47785613, 0.68471072,
        0.9624832 , 0.39938563, 0.38437599, 0.30809475, 0.7187551 ,
        0.5483733 , 0.20459374, 0.12169138, 0.63103612, 0.80130091,
        0.9371917 , 0.85402781, 0.07948946, 0.21948015, 0.12160676,
        0.31084436, 0.07757076, 0.03431393, 0.27692952, 0.00274948],
       [0.31780561, 0.94880636, 0.02436643, 0.92215088, 0.64121767,
        0.72793408, 0.4167476 , 0.43912997, 0.38605342, 0.16079372,
        0.08717807, 0.30283403, 0.39427684, 0.71326252, 0.22185533,
        0.70971686, 0.99690204, 0.47215299, 0.84290235, 0.48178371,
        0.39558277, 0.58570192, 0.65453131, 0.54150421, 0.55535591,
        0.59404304, 0.06243012, 0.75938583, 0.4

In [21]:
b[::-1]

array([[0.00274948, 0.27692952, 0.03431393, 0.07757076, 0.31084436,
        0.12160676, 0.21948015, 0.07948946, 0.85402781, 0.9371917 ,
        0.80130091, 0.63103612, 0.12169138, 0.20459374, 0.5483733 ,
        0.7187551 , 0.30809475, 0.38437599, 0.39938563, 0.9624832 ,
        0.68471072, 0.47785613, 0.60110283, 0.29331419, 0.21737581,
        0.9646393 , 0.2274656 , 0.806312  , 0.30101921, 0.15299047,
        0.40814953, 0.76458839, 0.75235967, 0.37062972, 0.44380126,
        0.82463731, 0.90283227, 0.70349131, 0.15352615, 0.30748721,
        0.25139021, 0.90687756, 0.7901206 , 0.11377441, 0.31687284],
       [0.58546197, 0.51742807, 0.21372183, 0.15707077, 0.1354164 ,
        0.92653978, 0.92938397, 0.69886856, 0.59534705, 0.99779529,
        0.24830338, 0.56454414, 0.56336078, 0.31459148, 0.7252508 ,
        0.14658096, 0.47958145, 0.75938583, 0.06243012, 0.59404304,
        0.55535591, 0.54150421, 0.65453131, 0.58570192, 0.39558277,
        0.48178371, 0.84290235, 0.47215299, 0.9

In [23]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
d = c.reshape((2,3))
d

ValueError: cannot reshape array of size 9 into shape (2,3)

In [25]:
d = c.reshape((2,2))
d

ValueError: cannot reshape array of size 9 into shape (2,2)

In [26]:
r = np.array([[1,2]])
r

array([[1, 2]])

In [27]:
t = np.arange(1,5)
t

array([1, 2, 3, 4])

In [28]:
t = np.array([1,2,0,3,4,0])
t

array([1, 2, 0, 3, 4, 0])

In [29]:
c = np.where(a!=0)
c

(array([], dtype=int64),)

In [30]:
t = np.array([1,2,0,3,4,0])
y = np.nonzero(t)
y

(array([0, 1, 3, 4], dtype=int64),)

In [34]:
import os

In [ ]:
path = Untitled Folder/aa.txt
with open('aa.txt', 'r') as file:
    data = file.read()
print(data)

In [35]:
os.dir(path)

AttributeError: module 'os' has no attribute 'dir'

In [ ]:
os.ldir

In [36]:
sub = lambda x,y:x-y

In [37]:
sub(10,5)

5

In [39]:
a = [1,2,3]
b = ['A','B','C']
d = dict(zip(a,b))
d

{1: 'A', 2: 'B', 3: 'C'}