In [1]:
#read n lines of file 
with open('filename','r') as file:
    for i in range(5):
        a = file.readlines()
        if not a:
            break
        print(a)

['----']


In [2]:
with open('filename','a') as file:
    file.write('Mayur')
with open('filename','r') as file:
    a = file.readlines()
print(a)

['----Mayur']


In [ ]:
#read last lines of file 
with open('filename','r') as file:
    a = file.readlines()
last = a[-5]
for i in last:
    print(i)

In [5]:
#read line by line & store in list
with open('filename','r') as file:
    a = file.readlines()
print(a)

['----Mayur']


In [6]:
a

['----Mayur']

In [8]:
#count number of lines in text file
with open('filename','r') as file:
    a = sum(1 for i in file)
print(a)

1


In [10]:
with open('filename','r') as file:
    a = sum(1 for i in file)
print(a)

1


In [12]:
from collections import Counter
with open('filename','r') as file:
    a = file.read().lower().split()
    b = Counter(a)
print(b)

Counter({'----mayur': 1})


In [13]:
import pandas as pd
import numpy as np

In [17]:
print(np.__version__)

1.23.5


In [18]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [19]:
a.nbytes

40

In [20]:
a[0]=99

In [21]:
a

array([99.,  0.,  0.,  0.,  0.])

In [22]:
a = np.arange(10,15)
a

array([10, 11, 12, 13, 14])

In [24]:
b = np.flip(a)
b

array([14, 13, 12, 11, 10])

In [26]:
c = a[::-1]
c

array([14, 13, 12, 11, 10])

In [27]:
a = np.array([3.44,4.44])
b = np.round(a)
b

array([3., 4.])

In [28]:
a = np.array([3.44,4.44])
b = np.ceil(a)
b

array([4., 5.])

In [29]:
a = np.array([3.44,4.44])
b = np.floor(a)
b

array([3., 4.])

In [30]:
a = np.array([[1,2,3],[4,5,6]])
b = np.mean(a)
b

3.5

In [31]:
a = np.array([[1,2,3],[4,5,6]])
b = np.mean(a, axis=1)
b

array([2., 5.])

In [32]:
a = np.array([[1,2,3],[4,5,6]])
b = np.mean(a, axis=0)
b

array([2.5, 3.5, 4.5])

In [33]:
a = np.array([0,45,90])
b = np.radians(a)
b

array([0.        , 0.78539816, 1.57079633])

In [34]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
a = np.array([[1,2,3],[4,5,6]])
b = np.flip(a, axis=1)
b

array([[3, 2, 1],
       [6, 5, 4]])

In [36]:
a = np.array([[1,2,3],[4,5,6]])
b = np.flip(a, axis=0)
b

array([[4, 5, 6],
       [1, 2, 3]])