In [1]:
# azAZ0-9
a = "mbnvdshbjERTYUBH @#$%^&7 4665"
b = a.isalnum()
b

False

In [5]:
import re
a = "mbnvdshbjERTYUBH @#$%^&7 4665"
b = re.findall(r'[a-zA-Z0-9]',a)
b

['m',
 'b',
 'n',
 'v',
 'd',
 's',
 'h',
 'b',
 'j',
 'E',
 'R',
 'T',
 'Y',
 'U',
 'B',
 'H',
 '7',
 '4',
 '6',
 '6',
 '5']

In [7]:
#spliy string by first orrurcane 
a = "mayur gohane"
b = a.split('a')
b

['m', 'yur goh', 'ne']

In [11]:
a = "mbnvdshbjERTYUBH @#$%^&7 4665"
b = re.findall(r"\d{3}",a)
b

['466']

In [12]:
a = "mbnvdshbjERTYUBH @#$%^&7 4665"
b = re.findall(r"\d",a)
b

['7', '4', '6', '6', '5']

In [14]:
#match string with ab 
a = "abb"
b = re.match(r'ab+',a)
b

<re.Match object; span=(0, 3), match='abb'>

In [16]:
a = "inform INFORM infrom"
if "inform" in a.casefold():
    print('yes')
else:
    print('no')

yes


In [17]:
a = "inform INFORM infrom"
if "inform" in a.lower().upper():
    print('yes')
else:
    print('no')

no


In [20]:
a = "abbbbbb"
b = re.findall(r'ab{2}',a)
b

['abb']

In [21]:
import numpy as np
import pandas as pd 

In [22]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [24]:
a.nbytes

40

In [25]:
a[4]=55
a

array([ 0.,  0.,  0.,  0., 55.])

In [26]:
a = np.arange(15,30)
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
b = a[::-1]
b

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [28]:
a = np.array([3.33,4.44])
b = np.round(a)
b

array([3., 4.])

In [29]:
c = np.ceil(a)
d = np.floor(a)
print(c)
print(d)

[4. 5.]
[3. 4.]


In [31]:
a

array([3.33, 4.44])

In [30]:
e = np.mean(a)
e

3.8850000000000002

In [33]:
a = np.array([77,88,99])
b = np.radians(a)
b

array([1.34390352, 1.53588974, 1.72787596])

In [35]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
a = np.array([[1,2,3],[4,5,6]])
b = np.flip(a)
b

array([[6, 5, 4],
       [3, 2, 1]])

In [37]:
a = np.array([[1,2,3],[4,5,6]])
b = np.flip(a, axis=1)
b

array([[3, 2, 1],
       [6, 5, 4]])

In [38]:
a = np.array([[1,2,3],[4,5,6]])
b = np.flip(a, axis=0)
b

array([[4, 5, 6],
       [1, 2, 3]])

In [39]:
a = np.array([1,0,8,0,6])
np.nonzero(a)

(array([0, 2, 4], dtype=int64),)

In [40]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.linalg.det(a)
b

0.0

In [42]:
a = np.array([[1,2,3],[0,5,0],[7,8,9]])
b = np.linalg.inv(a)
b

array([[-0.75      , -0.1       ,  0.25      ],
       [ 0.        ,  0.2       ,  0.        ],
       [ 0.58333333, -0.1       , -0.08333333]])

In [43]:
a = np.random.rand(30)
a

array([0.51346938, 0.82520452, 0.17158661, 0.88997059, 0.0973548 ,
       0.86964089, 0.07510631, 0.32536633, 0.33800976, 0.74105171,
       0.64896761, 0.88618647, 0.9953802 , 0.86893142, 0.84175764,
       0.81605391, 0.33569885, 0.38261795, 0.86850734, 0.83793157,
       0.69661294, 0.59135859, 0.66286419, 0.06097901, 0.93139655,
       0.97689838, 0.68801377, 0.71023063, 0.33302685, 0.92669867])

In [44]:
b = np.mean(a)
b

0.6302291144627996

In [45]:
a = np.random.rand(3,3,3)
a

array([[[0.6618262 , 0.62205874, 0.37104229],
        [0.53669896, 0.3133833 , 0.85024141],
        [0.33139823, 0.10222076, 0.30908604]],

       [[0.10118174, 0.31923212, 0.76113829],
        [0.93833964, 0.63066302, 0.25870513],
        [0.88190033, 0.44790734, 0.52825263]],

       [[0.21409198, 0.85366673, 0.8239627 ],
        [0.13478979, 0.54921512, 0.00600575],
        [0.88296388, 0.91889033, 0.63491507]]])

In [46]:
a = np.random.rand(30)
b = np.min(a)
c = np.max(a)
print(b)
print(c)

0.045390890054264
0.9620257777711729


In [47]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
a = np.random.rand(5,9)
b = np.random.rand(9,5)
c = np.dot(a,b)
c

array([[2.53096025, 1.96678316, 2.37345614, 3.19456958, 2.36174168],
       [2.95678833, 2.10607018, 3.13760655, 3.67378572, 2.85202643],
       [2.12535332, 2.40903667, 2.73102575, 3.01699625, 2.71802156],
       [1.54121914, 1.95656995, 2.22489679, 2.3220504 , 2.01913422],
       [2.65579933, 2.5573088 , 3.19652357, 3.54682401, 2.76648701]])

In [51]:
d = np.intersect1d(a,b)
d

array([], dtype=float64)

In [52]:
a = np.random.rand(10)
b = np.sort(a)
b

array([0.10780916, 0.18099096, 0.35076574, 0.44334947, 0.66523552,
       0.82026561, 0.83777168, 0.8571218 , 0.8957511 , 0.98494959])

In [55]:
a = np.tile(np.arange(10),(5,2))
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [58]:
b = np.arange(5).reshape(5,1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [60]:
a = np.array([1,2,3,4,5])
b = np.argmax(a)
a[b]= 99
a

array([ 1,  2,  3,  4, 99])

In [61]:
for i,v in np.ndenumerate(a):
    print(i,v)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 99


In [62]:
np.std(a)

38.61295119516249

In [63]:
from scipy import stats
stats.mode(a)

ModeResult(mode=1, count=1)

In [1]:
import pandas as pd 
import numpy as np

In [2]:
a = pd.Series([1,2,3])
a

0    1
1    2
2    3
dtype: int64

In [3]:
a = pd.Series([1,2,3],index=['a','b','c'])
a

a    1
b    2
c    3
dtype: int64

In [4]:
a = {
    'A':[1,2],
    'B':[3,4]}
b = pd.DataFrame(a)
b

A  B
0  1  3
1  2  4

In [5]:
c = b.empty
c

False

In [6]:
b

A  B
0  1  3
1  2  4

In [7]:
b.reindex(index=['X','XX'])

A   B
X  NaN NaN
XX NaN NaN

In [10]:
a = pd.Series([1,2])
b = pd.Series([3,4])
c = pd.concat([a,b], axis=1)
c

0  1
0  1  3
1  2  4

In [13]:
a = [['A',55,66],
    ['B',77,88]]

In [14]:
b = pd.DataFrame(a)
b

0   1   2
0  A  55  66
1  B  77  88

In [15]:
a = [1,2,3]
b = pd.DataFrame(a, columns=['A'])
b

A
0  1
1  2
2  3

In [16]:
a = np.random.rand(3,4)
b = pd.DataFrame(a,columns=['a','b','c','d'])
b

a         b         c         d
0  0.341722  0.354675  0.408286  0.918794
1  0.656980  0.863784  0.556256  0.794683
2  0.093013  0.376101  0.873989  0.341653

In [19]:
a = np.arange(30).reshape(10,3)
b = pd.DataFrame(a, columns=['a','b','c'])
b

a   b   c
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14
5  15  16  17
6  18  19  20
7  21  22  23
8  24  25  26
9  27  28  29

In [20]:
c = b.copy()
c

a   b   c
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14
5  15  16  17
6  18  19  20
7  21  22  23
8  24  25  26
9  27  28  29

In [21]:
b.set_index('a')

b   c
a         
0    1   2
3    4   5
6    7   8
9   10  11
12  13  14
15  16  17
18  19  20
21  22  23
24  25  26
27  28  29

In [22]:
b

a   b   c
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14
5  15  16  17
6  18  19  20
7  21  22  23
8  24  25  26
9  27  28  29

In [23]:
b.columns

Index(['a', 'b', 'c'], dtype='object')

In [26]:
b.rename(columns={'a':'x','b':'xx','c':'xxx'}, inplace=True)
b

x  xx  xxx
0   0   1    2
1   3   4    5
2   6   7    8
3   9  10   11
4  12  13   14
5  15  16   17
6  18  19   20
7  21  22   23
8  24  25   26
9  27  28   29

In [27]:
b.columns

Index(['x', 'xx', 'xxx'], dtype='object')

In [28]:
b['x']=b['x'].apply(lambda x: x +10)

In [29]:
b

x  xx  xxx
0  10   1    2
1  13   4    5
2  16   7    8
3  19  10   11
4  22  13   14
5  25  16   17
6  28  19   20
7  31  22   23
8  34  25   26
9  37  28   29

In [30]:
b[['x','xx','xxx']]=b[['x','xx','xxx']].apply(lambda x: x +10)

In [31]:
b

x  xx  xxx
0  20  11   12
1  23  14   15
2  26  17   18
3  29  20   21
4  32  23   24
5  35  26   27
6  38  29   30
7  41  32   33
8  44  35   36
9  47  38   39

In [32]:
c = b.to_numpy()
c

array([[20, 11, 12],
       [23, 14, 15],
       [26, 17, 18],
       [29, 20, 21],
       [32, 23, 24],
       [35, 26, 27],
       [38, 29, 30],
       [41, 32, 33],
       [44, 35, 36],
       [47, 38, 39]], dtype=int64)

In [33]:
b.values

array([[20, 11, 12],
       [23, 14, 15],
       [26, 17, 18],
       [29, 20, 21],
       [32, 23, 24],
       [35, 26, 27],
       [38, 29, 30],
       [41, 32, 33],
       [44, 35, 36],
       [47, 38, 39]], dtype=int64)

In [34]:
d = b.values.tolist()
d

[[20, 11, 12],
 [23, 14, 15],
 [26, 17, 18],
 [29, 20, 21],
 [32, 23, 24],
 [35, 26, 27],
 [38, 29, 30],
 [41, 32, 33],
 [44, 35, 36],
 [47, 38, 39]]

In [36]:
b.head(5)

x  xx  xxx
0  20  11   12
1  23  14   15
2  26  17   18
3  29  20   21
4  32  23   24

In [38]:
a = {'A':['X','XX'],
    'B':[3,4]}
b = pd.DataFrame(a)
b

A  B
0   X  3
1  XX  4

In [39]:
mapp = {3:'ZZ',4:'ZZZ'}
b['new'] = b['B'].map(mapp)
b

A  B  new
0   X  3   ZZ
1  XX  4  ZZZ

In [ ]:
b.insert(1,'LL',[55,6])

In [47]:
b

A  LL  B  new
0   X  55  3   ZZ
1  XX   6  4  ZZZ

In [50]:
b.drop('A',axis=1,inplace=True)

In [51]:
b

LL  B  new
0  55  3   ZZ
1   6  4  ZZZ

In [53]:
b['B'].quantile(0.25)

3.25