In [1]:
#square of first 5 and last 5 number 
def square(f,l):
    a =[]
    for i in range(f,f+5):
        a.append(i**2)
    for i in range(l-4,l+1):
        a.append(i**2)
    return a

In [2]:
square(5,15)

[25, 36, 49, 64, 81, 121, 144, 169, 196, 225]

In [7]:
#factorial 

def fact(n):
    f = 1
    for i in range(1,n+1):
        f = f * i
    print(f)

In [8]:
fact(5)

120


In [11]:
# factorial using user defined function
def factt(n):
    fact = 1
    for i in range(1,n+1):
        fact = fact * i
    print(fact)

In [12]:
factt(5)

120


In [13]:
add = lambda x,y: x+y

In [14]:
add(5,5)

10

In [16]:
a = ['A','B','C']
b = [25,25,95]
c = dict(zip(a,b))

In [17]:
c

{'A': 25, 'B': 25, 'C': 95}

In [18]:
a = ['A','B','C']
b = [25,25,95]
c = tuple(zip(a,b))
c

(('A', 25), ('B', 25), ('C', 95))

In [19]:
a = ['A','B','C']
b = [25,25,95]
c = list(zip(a,b))
c

[('A', 25), ('B', 25), ('C', 95)]

In [20]:
a = ['A','B','C']
b = [25,25,95]
tuple(zip(a,b))

(('A', 25), ('B', 25), ('C', 95))

In [21]:
a = ['A','B','C']
b = [25,25,95]
dict(zip(a,b))

{'A': 25, 'B': 25, 'C': 95}

In [24]:
a = "Python and Machine Learning"
b = list(filter(lambda x: x.isupper(),a))
b

['P', 'M', 'L']

In [25]:
a = "Python and Machine Learning"
b = list(map(lambda x: x.upper(),a))
''.join(b)

'PYTHON AND MACHINE LEARNING'

In [26]:
a = [1,2,3,4,5,6,7,8,9]
b = list(map(lambda x: x**2,a))
b

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [28]:
a = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
b = list(filter(lambda x: len(x)==6,a))
b

['Sunday', 'Monday', 'Friday']

In [30]:
a = "2 + 66 ** 22"
b = eval(a)
b

10714368571740915734427767689504050118658

In [31]:
a = 2 + 66 ** 22
a

10714368571740915734427767689504050118658

In [32]:
divmod(5,5)

(1, 0)

In [33]:
divmod(25,5)

(5, 0)

In [34]:
divmod(25,4)

(6, 1)

In [37]:
class car:
    def start(self):
        print('car starting')
my = car()
my.start()

car starting


In [38]:
class A:
    def bb(self):
        print('AA')
b = A()
b.bb()

AA


In [42]:
class Car:
    pass
    def price(self):
        p = 5
        print('price is',p)
a = Car()
a.price()

price is 5


In [44]:
#inint methods
class dog:
    def __init__(self,name):
        self.name=name
    def bark(self):
        print(f'{self.name} says Hii')
a = dog('XXX')
a.bark()

XXX says Hii


In [46]:
class car:
    def __init__(self,name):
        self.name=name
    def start(self):
        print(f"{self.name} is Started")
a = car('TATA')
a.start()

TATA is Started


In [50]:
class cal:
    def addition(self,a,b):
        self.a=a
        self.b=b
        add = a+b
        print(add)
        
    def mult(self):
        multt = self.a * self.b
        print(multt)

    def divide(self):
        div = self.a / self.b
        print(div)
a = cal()
a.addition(5,5)
a.mult()
a.divide()

10
25
1.0


In [51]:
class cal:
    def addition(self,a,b):
        self.a=a
        self.b=b
        add = a+b
        #print(add)
        
    def mult(self):
        multt = self.a * self.b
        #print(multt)

    def divide(self):
        div = self.a / self.b
        #print(div)

a = cal()
a.addition(5,5)
a.mult()
a.divide()

In [54]:
class call:

    def __init__(self,a,b):
        self.a=a
        self.b=b

    def addition(self):
        add = self.a + self.b
        print(add)

    def sub(self):
        s = self.a - self.b
        print(s)
        
a = call(5,5)
a.addition()
a.sub()

10
0


In [55]:
class a:
    pass
class b(a):
    pass

In [56]:
a = b()

In [57]:
a

In [ ]:
class animal:
    def __init__(self,name):
        self.name=name
    def sound(self):
        print('Animal sound')
class dog(animal):
    def __init__(self,name):
        super().__init__(name)
        

In [58]:
from abc import ABC, abstractmethod

In [59]:
class A(ABC):
    pass
class B(A):
    pass

In [60]:
import pandas as pd
import numpy as np

In [61]:
pd

<module 'pandas' from 'C:\\Users\\LEGION\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pandas\\__init__.py'>

In [62]:
np

<module 'numpy' from 'C:\\Users\\LEGION\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>

In [63]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [64]:
a = np.array([1,2,3], dtype='float')
a

array([1., 2., 3.])

In [65]:
a = np.array(10)
a

array(10)

In [68]:
a = np.array([10])
a

array([10])

In [69]:
a.shape

(1,)

In [70]:
b = np.array([[10]])
b

array([[10]])

In [71]:
b.shape

(1, 1)

In [72]:
c = np.array([[10],[55]])
c

array([[10],
       [55]])

In [74]:
c.shape

(2, 1)

In [75]:
e = np.array([[[10]]])
e

array([[[10]]])

In [76]:
e.shape

(1, 1, 1)

In [77]:
e.ndim

3

In [79]:
a = np.array([1,2,3,4,5])
a[0]=55
a

array([55,  2,  3,  4,  5])

In [81]:
a[:2]

array([55,  2])

In [82]:
b = np.array([[4,5], [9,7], [8,6]])
b

array([[4, 5],
       [9, 7],
       [8, 6]])

In [84]:
b[0][0] = 88

In [85]:
b

array([[88,  5],
       [ 9,  7],
       [ 8,  6]])

In [86]:
b[0][0],[0],[1] = 99

SyntaxError: cannot assign to literal (109614822.py, line 1)

In [88]:
b[0:1,1:2]

array([[5]])

In [89]:
b

array([[88,  5],
       [ 9,  7],
       [ 8,  6]])

In [90]:
b[:,1:2]

array([[5],
       [7],
       [6]])

In [93]:
b[:,1]

array([5, 7, 6])

In [94]:
b[:,]

array([[88,  5],
       [ 9,  7],
       [ 8,  6]])

In [100]:
b[0,0]

88

In [101]:
b[0,1]

5

In [102]:
b[1,0]

9

In [103]:
b

array([[88,  5],
       [ 9,  7],
       [ 8,  6]])

In [105]:
b = np.array([[4,5], [9,7], [8,6]], ndmin=2)
b

array([[4, 5],
       [9, 7],
       [8, 6]])

In [106]:
b = np.array([[4,5], [9,7], [8,6]], ndmin=4)
b

array([[[[4, 5],
         [9, 7],
         [8, 6]]]])

In [107]:
b = np.array([[4,5], [9,7], [8,6]], ndmin=1)
b

array([[4, 5],
       [9, 7],
       [8, 6]])

In [108]:
b = np.array([[4,5], [9,7], [8,6]], ndmin=4)
b

array([[[[4, 5],
         [9, 7],
         [8, 6]]]])

In [109]:
b = np.array([[4,5], [9,7], [8,6]], ndmin=5)
b

array([[[[[4, 5],
          [9, 7],
          [8, 6]]]]])

In [112]:
b = np.array([[4,5], [9,7], [8,6]])
b = b.reshape(6,1)
b

array([[4],
       [5],
       [9],
       [7],
       [8],
       [6]])

In [113]:
b = np.array([[4,5], [9,7], [8,6]])
c = b.flatten()
c

array([4, 5, 9, 7, 8, 6])

In [114]:
b = np.array([[4,5], [9,7], [8,6]])
c = b.reshape(-1)
c

array([4, 5, 9, 7, 8, 6])

In [116]:
a = np.zeros((4,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [117]:
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [118]:
a = np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [122]:
a = np.random.rand(10)
b

array([[4, 5],
       [9, 7],
       [8, 6]])

In [124]:
a = np.random.rand(10)
''.join([str(int(i)) for i in a])

'0000000000'

In [127]:
a = np.random.randint(10, size=(2,5))
a

array([[5, 6, 0, 6, 6],
       [3, 9, 3, 8, 9]])

In [131]:
a = np.random.randint(5,15)
a

7

In [132]:
a = np.random.randint(5,15, size=(5,3))
a

array([[13,  7,  5],
       [ 7,  6, 12],
       [ 5, 10,  8],
       [ 6,  9,  7],
       [ 5, 13,  9]])

In [135]:
b = np.sort(a)
b

array([[ 5,  7, 13],
       [ 6,  7, 12],
       [ 5,  8, 10],
       [ 6,  7,  9],
       [ 5,  9, 13]])

In [136]:
from scipy import stats 

In [137]:
c = stats.mode(b)
c

ModeResult(mode=array([ 5,  7, 13], dtype=int64), count=array([3, 3, 2], dtype=int64))

In [138]:
np.mean(b)

8.133333333333333

In [139]:
np.median(b)

7.0

In [140]:
np.std(b)

2.7047283700134392

In [141]:
np.var(b)

7.315555555555557

In [151]:
A = np.array([[2,3,5],[1,-2,3]])
B = np.array([10,15,30])

In [155]:
np.log(10)

2.302585092994046

In [156]:
np.log10(10)

1.0

In [157]:
np.log2(10)

3.321928094887362

In [158]:
a = np.array([1,2,3,4,5])

In [159]:
b = np.rad2deg(a)
b

array([ 57.29577951, 114.59155903, 171.88733854, 229.18311805,
       286.47889757])

In [160]:
c = np.radians(a)
c

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646])

In [161]:
d = np.deg2rad(a)
d

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646])

In [162]:
e = np.sin(a)
e

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [163]:
d = np.cos(a)
d

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [164]:
f = np.tan(a)
f

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [165]:
g = np.append(d,f)
g

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [168]:
g = np.append(d,f).astype(float)
g

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [169]:
g = np.append(d,f)
g

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [170]:
for i in np.nditer(g):
    print(i)

0.5403023058681398
-0.4161468365471424
-0.9899924966004454
-0.6536436208636119
0.28366218546322625
1.5574077246549023
-2.185039863261519
-0.1425465430742778
1.1578212823495777
-3.380515006246586


In [172]:
for i,v in np.ndenumerate(g):
    print(i,v)

(0,) 0.5403023058681398
(1,) -0.4161468365471424
(2,) -0.9899924966004454
(3,) -0.6536436208636119
(4,) 0.28366218546322625
(5,) 1.5574077246549023
(6,) -2.185039863261519
(7,) -0.1425465430742778
(8,) 1.1578212823495777
(9,) -3.380515006246586


In [173]:
np.ceil(g)

array([ 1., -0., -0., -0.,  1.,  2., -2., -0.,  2., -3.])

In [174]:
np.floor(g)

array([ 0., -1., -1., -1.,  0.,  1., -3., -1.,  1., -4.])

In [176]:
np.round(g)

array([ 1., -0., -1., -1.,  0.,  2., -2., -0.,  1., -3.])